services:

  web:
    build: .
    volumes:
      - ./:/var/www:cached
      - ./templates/default.conf:/etc/apache2/sites-available/000-default.conf
      - ./templates/apache2.conf:/etc/apache2/apache2.conf
    ports:
      - 8081:80
    networks:
      net:
    depends_on:
      - db

  db:
    image: mariadb
    volumes:
      - ./templates/custom.cnf:/etc/mysql/conf.d/custom.cnf
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: ebms
      MYSQL_DATABASE: ebms
      MYSQL_USER: ebms
      MYSQL_PASSWORD: ebms
    networks:
      net:

  mailhog:
    image: teawithfruit/mailhog
    ports:
      - 8025:8025
    networks:
      net:

  chrome:
    # See https://github.com/SeleniumHQ/docker-selenium/issues/2291.
    image: seleniarm/standalone-chromium:4.1.4-20220429
    volumes:
      - ./testdata/browser:/usr/local/share/testdata
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
    ports:
      - '5900:5900'
      - '7900:7900'
      - '4444:4444'
    shm_size: 2g
    networks:
      net:

networks:
  net:
